import "./globals.css";
import Header from "../components/Header";
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="bg-gray-900 text-gray-100 w-full h-[100vw] scroll-smooth">
        <Header />
        <main className="w-[60%] mx-auto grid">{children}</main>
      </body>
    </html>
  );
}
